#!/bin/bash

# Check if autossh is not already running
pgrepPid=`pgrep autossh`
if [ "$?" -eq 0 ]
then
  echo "Autossh already running with PID $pgrepPid => Exiting" >&2;
  exit 1
fi


### Loading OGN config
# Need this hack to allow sourcing from a file in dos format
source /dev/stdin < <(dos2unix < /boot/OGN-receiver.conf)

if [ "$EnableCoreOGNTeamRemoteAdmin" != "true" ]
then
  echo "Remote admin not enabled => Exiting" >&2
  exit 0;
fi

echo "Checking internet connection." >&2
/usr/bin/wget --spider --quiet "http://mail.rvss.ca/"
if [ "$?" -ne 0 ]
then
  echo "Not Connected => Exiting" >&2
  exit 1
fi
echo "Connected." >&2

if [ "$ReceiverName" == "CPL3" ]; then
   monitorPort=6000
elif [ "$ReceiverName" == "FALLFLD" ]; then
   monitorPort=6020
elif [ "$ReceiverName" == "Fallfld3" ]; then
   monitorPort=6040
elif [ "$ReceiverName" == "GlebeON" ]; then
   monitorPort=6060
elif [ "$ReceiverName" == "PerthON" ]; then
   monitorPort=6080
elif [ "$ReceiverName" == "TglwoodON" ]; then
   monitorPort=6100
elif [ "$ReceiverName" == "WinghamON" ]; then
   monitorPort=6120
fi

if [ "$?" -eq 0 ]
then
 echo "Ok ${port}" >&2
  /usr/bin/autossh -f -N -R $monitorPort:localhost:22 autossh@mail.rvss.ca -M $(($monitorPort+1060)) -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3"
  exit 0
fi
exit 1
