#!/bin/bash

### Loading OGN config
# Need this hack to allow sourcing from a file in dos format
source /dev/stdin < <(dos2unix < /boot/OGN-receiver.conf)

if [ "$sendLogs" != "true" ]
then
  echo "Not sending logs. Feature not enabled. => Exiting" >&2
  exit 0;
fi

# directory containing the log files (same for this receiver and remote ATM)
logDir="/data/ogn/log/"

# This file contains the rsync log
rsyncStats="${logDir}${ReceiverName}-$(date '+%Y%m%d')-rsync-stats.log"

# This pattern identifies the log files to send. In particular, it
# ensure that only log files belonging to the configured receiver are sent.
# It is a guard against the case where a receiver had a previous name.
rsyncPattern="${logDir}${ReceiverName}-$(date '+%Y%m%d')*.log"

# This command ensures a very efficient rsync transfer. Log files will
# tend to grow as the day goes on. The command appends data to existing
# files or replaces entire files if required. Transfers are compressed.  
/usr/bin/rsync -e "ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --log-file=${rsyncStats} --compress-level=9 --archive --append-verify ${rsyncPattern} ognstation@ogn.rvss.ca:${logDir}
